# Environment variable cleanup script
# Generated by unycode auth CLI

Write-Host "Clearing conflicting environment variables..." -ForegroundColor Yellow

Remove-Item Env:ANTHROPIC_AUTH_TOKEN -ErrorAction SilentlyContinue
if (Test-Path Env:ANTHROPIC_AUTH_TOKEN) {
    Write-Host "⚠️  Could not clear ANTHROPIC_AUTH_TOKEN" -ForegroundColor Red
} else {
    Write-Host "✓ Cleared ANTHROPIC_AUTH_TOKEN" -ForegroundColor Green
}

Write-Host "`nEnvironment variable cleanup completed!" -ForegroundColor Green
Write-Host "You can now run your AI CLI commands without conflicts." -ForegroundColor Cyan
